# Generated by Django 5.2.7 on 2025-11-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('valeur', models.TextField()),
                ('image', models.ImageField(upload_to='static/image/sliders')),
            ],
        ),
    ]
