# Generated by Django 5.2.7 on 2026-02-14 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='valeur',
            new_name='titre',
        ),
    ]
